#cloud-config
# Install git and pip
package_update: true
package_upgrade: true
packages:
  - python3-pip

runcmd:
  # Create ansible user
  - useradd -m ansible-user
  - usermod -aG adm ansible-user
  - echo -e "ansible-user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
  # Add .ssh directory and private key file
  - runuser -l ansible-user -c 'mkdir ~/.ssh'
  - runuser -l ansible-user -c 'chmod 700 ~/.ssh'
  - |
    runuser -l ansible-user -c 'echo "-----BEGIN OPENSSH PRIVATE KEY-----
    *****
    -----END OPENSSH PRIVATE KEY-----" > .ssh/id_rsa'
    runuser -l ansible-user -c 'chmod 600 .ssh/id_rsa'

    runuser -l ansible-user -c 'pip install ansible awscli boto3'

    runuser -l ansible-user -c 'mkdir .aws'
    runuser -l ansible-user -c 'echo "[default]
    aws_access_key_id=*****
    aws_secret_access_key=*****" > .aws/credentials'

    runuser -l ansible-user -c 'aws s3 cp s3://rs-s3-bucket/rs-demo.tgz rs-demo.tgz'
    runuser -l ansible-user -c 'tar -xf rs-demo.tgz' 
    runuser -l ansible-user -c 'ansible-playbook -i inventory_aws_ec2.yaml main.yaml'
